Contact form
AminaBuhari/Portfolio-Project- pull request #3
Opened 2022-02-15 22:37 UTC by AminaBuhari

I collaborated with my partner @RaoAkif and created a contact form in my portfolio project. We updated:
1. The index.html file and added a contact section.
2. The style.css according to the figma template given to us.
3. We added a free form link which allows contact forms filled to be redirected to the email provided.

2022-02-15 23:20 UTC, Donard97 requested changes
## Hi @AminaBuhari , 👋 

_You did an amazing job so far! 👏 💯 💯_ 

There are some issues that you still need to work on to go to the next project but you are almost there! 👍 

![giphy (4)](https://user-images.githubusercontent.com/74506933/154166402-92d8fdad-75c9-4e5e-aa60-8b5c06c41c4a.gif)

## Required Changes ♻️

- [ ] Please check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-15 23:20 UTC, Donard97 commented on index.html
> +        </div>
- [ ] You did an amazing job add contact form section but kindly change it to footer tag as it was part of [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md). Keep rocking 💪

2022-02-15 23:20 UTC, Donard97 commented on index.html
> +        </form>
- [ ] Good job on adding button but please stick as much as you can to [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) and kindly add button interactions as it is shown on design:

![image](https://user-images.githubusercontent.com/74506933/154165875-b279512d-2a91-49e5-ac5b-cb02623103e3.png)

2022-02-15 23:20 UTC, Donard97 commented on index.html
> +            </h3>
- [ ] Please change font of the heading following [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468). Keep coding 💪

2022-02-16 12:08 UTC, gemmen29 approved these changes
Hi @AminaBuhari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 12:40 UTC, merged